### ISSUE TITLE
Materjali lisamine tavakasutaja poolt

### ISSUE THREAD

**Issue by erkkijakobson** [e-koolikott/DOP#1]
**Eesmärk:** lihtsustada uue õppevara lisamist

**Tänane olukord:** otse FAB-menüüst saavad materjale lisada Sisutootja ja Admin rollid

**Vajadus:** anda sama õigus ka tavakasutaja rollile

**Comment by martlausNG** [comment]
Resolved in https://github.com/e-koolikott/DOP-Front-End/
