### ISSUE TITLE
Waramu õppevara metaandmete muutmine

### ISSUE THREAD

**Issue by erkkijakobson** [e-koolikott/DOP#23]
Admin ja aineeksperdi roll peavad omama õigust waramu õppevara metaandmeid sh pilti muuta

- [x] Kui materjali link pole repo oma (vaja on repode materjalide baas URL-e), siis sünkroniseerimise käigus materjali ei uuendata - (kõikide repode puhul). Seega on materjali "omanik" eKoolikott

- [x] Repode sünkroniseerimisel (nt waramu) uuendatakse süsteemis ainult välju, mis pole tühjad (NULL-id vms) OAI-PMH Record objektis 

- [x] Repo lingiga materjalide uuendamine jääb samaks, ehk kui üle OAI-PMH tulevas väljas (nt pealkiri) on info ning see on ka eKoolikotis, siis see kirjutatakse üle repo infoga (ehk baasis asendatakse e-koolikoti pealkirja väli repo omaga )

- [x] Kui väljal on e-Koolikotis väärtus ning sünkronisatsiooni käigus tuleb repost antud väli NULL-ina, siis teda üle ei kirjutata ning säilib väärtus

- [x] Frondis repode materjalide muutmise funktsionaalsuse lisamine

Tulemid:
- [x] Materjalide uuendamiseloogika ehitamine olenevalt tema päritolust
- [x] Sünkronisatsioonil materjali lingi kontroll ja selle järgi uuendamisloogika kasutamine
- [x] Waramu materjalide muutmise lubamine süsteemselt, konfliktide lahendamine
- [x] Waramu materjalide muutmise lubamine frondis
- [x] Iga repositooriumi baaslinkide tabeli ja relatsiooni loomine

**Comment by martlausNG** [comment]
Needs review.

**Comment by Jointts** [comment]
Review OK.
