### ISSUE TITLE
Aineeksperdi roll

### ISSUE THREAD

**Issue by erkkijakobson** [e-koolikott/DOP#24]
Luua uus süsteemne roll aineekspert (moderaator), esmased õigused:

- [x] hallata õppevara metat sh pilte v.a. kirjastuselt automaatliidesega tulevate materjalide puhul

- [x] näha Töölaual raporteeritut, kustutatud õppevara - sama nagu eelnevalt admin roll

- [x] lisada kasutuspiirangut (piiratud kasutaja rolli) ebasobiva õppevara detailvaates selle lisajale

Kõik aineeksperdi õigused on alati ka admin rollil

**Comment by martlausNG** [comment]
Needs review
