### ISSUE TITLE
Tarkvarajärgu kuvamine

### ISSUE THREAD

**Issue by erkkijakobson** [e-koolikott/DOP#25]
- [x] rakendada semantilist versioneerimist http://semver.org/

- [x] keskmine number = github milestone

- [x] kuvada versiooninumber helehallilt rakenduse vasakul all nurgas

- [x] versiooninumbril klikkimine toob githubi tarnemärkmetele

- [x] avatud vasakmenüü element on versiooninumbrist z-teljel eespool ehk katab seda.

Tulemid:
- [x] Järgu kuvamine ja disain frondis
- [x] Järgu küsimise teenus
- [x] Changelogi linkimine ja loomine

**Comment by martlausNG** [comment]
Needs review.

**Comment by erkkijakobson** [comment]
murdepunktil gt-md ok, alla selle tuleb sisu peale

**Comment by Jointts** [comment]
Review OK.
