### ISSUE TITLE
Materjali lisamisel väljade kohustuslikkus karmimaks

### ISSUE THREAD

**Issue by erkkijakobson** [e-koolikott/DOP#3]
Kasutajapoolne kohtustus määrata:

**Põhiandmed**
- [x] link
- [x] õppematerjali keel
- [x] pealkiri
- [x] pealkirja ja kirjelduse keel (vakimisi eelvalitud üleslaadija kasutajaliidese keele põhjal)
- [x] tüüp (peab olema tähestiku järjekorras ja kas mitmes tulbas vm aga mitte dialoogi laiusena nimekirjana)

**Liigitus**
- [x] haridustase (edaspidi peab olema võimalik valida mitut, mitte ei lukustu see ühe valikuga)
- [x] taksonoomiapuust peab olema valitud vähemalt ühel real Teema
- [x] läbivad teemad: rippmenüüsse juurde lisavalik (pole vaikevalik) "ei käsitle läbivaid teemasid"=baasi ei lähe midagi
- [x] üldpädevused: juurde lisavalik (pole vaikevalik)"ei seostu üldpädevuste kujundamisega"=baasi ei lähe midagi
- [x] vanus, kooliaaste või klass (tase->keskharidus puhul läheb eelvalituks gümnaasiumi aste)

**Lisaandmed**
- [x] autori ees- ja perekonnanimi või väljaandja
- [x] litsentsi tüüp (rippmenüüsse juurde lisavalik "ei oska valida"=baasi läheb 'Kõik õigused kaitstud')
- [x] väljalaskmise aeg (peab olema võimalik määrata ka ainult aasta)

- [x] peab saama vajutada Lisa ilma ühtki eelnevast täitmata, mis teeb kohustulikud punaseks, peab näitama ka millises 3 vahekaardist on täitmata välju

**Comment by martlausNG** [comment]
Needs review
