### ISSUE TITLE
Otsingu lehel ei tühista "Tühista valikud" haridustaset

### ISSUE THREAD

**Issue by KailiAll** [e-koolikott/DOP#47]
**Arendusvajaduse kirjeldus:**
1. Ava täpne otsing
2. Haridustase- klõpsad noolekesel
3. Avaneb haridustaseme nimekiri. 
4. Teed ühe valiku
5. Klõpsad "Tühista valikud"
6. Valikud ei tühistata- see on viga

**Tulem:**
- [ ] Valikute tühistamine tühistab haridustaseme valiku

**Comment by martlausNG** [comment]
Needs review
