### ISSUE TITLE
Otsing tüübi põhjal

### ISSUE THREAD

**Issue by erkkijakobson** [e-koolikott/DOP#5]
Detailotsingu kasti lisada materjali tüübi põhjal filtreerimine.
- [x]  Front-end-i Advanced search-i kasti uus dropdown
- [x]  Solrisse välja lisamine
- [x]  Solris antud välja jälgimine, indekseerimine, uuendamine
- [x]  Back-endi integratsioon Solriga, et antud välja küsida
- [x]  Back-endi Unit testid
- [x]  Automaattestid, regressioonitestid - testijate poolt.

**Comment by martlausNG** [comment]
Needs review,
