### ISSUE TITLE
Kogumiku peatükkide sisu ei ole näha

### ISSUE THREAD

**Issue by erkkijakobson** [e-koolikott/DOP#55]
Sammud
1. ava kogumik
2. näha peab olema sama detailvaade nagu materjalil=sama mall (#17)
3. avades vasakmenüüst peatüki ei ole selle sisu (materjale) enam näha, vasakmenüü ei sulgu peatükki avades
Testitud Firefoxiga, esineb vaid kitsal murdepunktil

**Comment by Jointts** [comment]
Review OK.
