### ISSUE TITLE
Search-As-You-Type rakendamine

### ISSUE THREAD

**Issue by erkkijakobson** [e-koolikott/DOP#6]
- [x] Front-endi implementatsioon, et toetada otsingut trükkimise ajal
- [x]  Front-endi optimiseerimine suurenevate päringuhulkade tõttu
- [x]  Otsingu reeglistiku ehitamine - millal algab otsing, vanade päringute tühistamine
- [ ]  Automaattestid, regressioonitestid - testijate poolt.

**Comment by martlausNG** [comment]
Needs review

**Comment by erkkijakobson** [comment]
query kustutamisel jäävad lihtotsingus viimased 2 tähte, detailotsingus 1 täht URLi püsima
