### ISSUE TITLE
Puuduvad waramu materjalid

### ISSUE THREAD

**Issue by erkkijakobson** [e-koolikott/DOP#62]
Tuvastatud on hulk materjale, mis ei ole jõudnud kohale, nt:
https://koolielu.ee/waramu/search/sort/created/_fulltext/makey
https://e-koolikott.ee/search/result?q=makey

**Comment by martlausNG** [comment]
Tundub, et waramu poolt ei tule materjali sisu, kui on XML estcore formaadis (Kirjeldus ja pealkiri on puudu):
**oai_lom vorming**:
http://koolitaja.eenet.ee:57219/Waramu3Web/OAIHandler?verb=GetRecord&metadataPrefix=oai_lom&identifier=1-f8f022eb-2511-490f-98b5-d2f9d7e3c4bb

**oai_estcore vorming**:
http://koolitaja.eenet.ee:57219/Waramu3Web/OAIHandler?verb=GetRecord&metadataPrefix=oai_estcore&identifier=1-f8f022eb-2511-490f-98b5-d2f9d7e3c4bb

**Comment by erkkijakobson** [comment]
parandatud waramu poolt
